### ISSUE TITLE
Prevent checking in `nofile` buffers.

### ISSUE THREAD

**Issue by spimanov** [lukoshkin/trailing-whitespace#1]
Hello!
I'd suggest to prevent checking in nofile buffers (e.g. clangd lsp shows documentation using a bit strange markdown format, which leads to highlighting trailing spaces in floating windows)
The following lines in the beginning of the `tws.match_tws ()` function  help to avoid the problem:
```
  if vim.bo.buftype == "nofile" or vim.bo.buftype == "terminal" then
    return
  end
```
Thank you!

**Comment by lukoshkin** [comment]
Hey @spimanov!
Sorry, I missed the notification. Or maybe that is because you didn't assign anyone to the issue. Anyway, I updated the master branch. Could you check your problem again after pulling the updates and removing your adjustments from the source code?

Though I don't expect, it will work for you. Since I only excluded floated and all non-normal windows from highlighting them with `tws.match_tws`. The patch is mainly about other stuff.

If it is not working, I will add to the configuration something like blacklist table, where you can specify buftypes to ignore.

Thanks for opening an issue!

**Comment by lukoshkin** [comment]
I guess it is no longer an issue. Anyone concerned with related problems can reopen it
